name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # Python
          pip install -r requirements.txt
          sudo apt-get install -y gettext
          # Go
          curl -OL https://github.com/transifex/cli/releases/download/v1.6.5/tx-linux-amd64.tar.gz
          tar -xvzf tx-linux-amd64.tar.gz

      - name: Pull then push translation strings
        env:
          tx_token: ${{ secrets.TX_TOKEN }}
        run: |
          TX_TOKEN=$tx_token make transifex_pull
          TX_TOKEN=$tx_token make transifex_push

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update .tx/config

      - name: build
        run: |
          make html
          touch build/html/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/build/html
